name: Gerar APK Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Instalar dependências
        run: npm install

      - name: Recriar projeto Android
        run: |
          rm -rf android
          npx cap add android
          npx cap sync android

      - name: Gerar APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: YZAT-Almoxarifado-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
